### ISSUE TITLE
Query metafields in product query

### ISSUE THREAD

**Issue by chrispreisler** [thetre97/gridsome-source-shopify#17]
Hey guys,

it would be awesome, if you add the possibility to also query for metafields in the product query.

Thank you very much for your answer in advance.

Best regards
Chris

**Comment by travis-r6s** [comment]
@chrispreisler Good idea - I'll start looking into adding that.

**Comment by chrispreisler** [comment]
Thank you very much.

**Comment by travis-r6s** [comment]
@chrispreisler Sorry for the delay in this - but have added this. 
To make metafields available in the Storefront API, you will need to follow this guide: https://shopify.dev/tutorials/retrieve-metafields-with-storefront-api

**Comment by chrispreisler** [comment]
No problem, thank you very much. That sounds awesome. Where would I have to make that "Whitelistening" Mutation? Int the Gridsome Server? Or do you I have to use an extra tool to do that? Or can I do that from the Shopify Backend? 

It's crazy, that it is so complicated to get the metafields via the api ...

Thanks for your help i advance again.

Best regards
Chris

**Comment by chrispreisler** [comment]
@thetre97 Would it be possible to point me in the right direction? I tried for myself, but unfortunatley didn't get my head around it. Thank you so much.
