### ISSUE TITLE
Add MaxWidth and MaxHeight to Queries

### ISSUE THREAD

**Issue by chrispreisler** [thetre97/gridsome-source-shopify#31]
Hey @thetre97,

it would be awesome if you can add maxWidth and maxHeight to the image queries. It would help calculate the image ratios to better work with lazy loading.

https://shopify.dev/docs/storefront-api/reference/object/image

Thank you very much.

Best regards
Chris

**Comment by travis-r6s** [comment]
@chrispreisler It should already have this option - https://github.com/thetre97/gridsome-source-shopify#transformsrc

**Comment by chrispreisler** [comment]
As I understand it, I can only get a transformed image with this options, but I would like to get the values of maxWidth and maxHeight like this. This gives me an error right now:

Cannot query field "maxWidth" on type "ShopifyImage"

```
images(limit: 10) {
  id
  originalSrc
  altText
  maxWidth
  maxHeight
}
```

**Comment by travis-r6s** [comment]
I don't believe they are actually fields, they are arguments for the `transformSrc` field.

So you specify the `maxWidth` & `maxHeight` as needed.

**Comment by chrispreisler** [comment]
As I read it right, in this link they are actual fields like originalSrc and altText. Or am I wrong?

https://shopify.dev/docs/storefront-api/reference/object/image

**Comment by travis-r6s** [comment]
If you look at the way they have written the docs, the arguments are typed as code blocks (`crop` etc):
![image](https://user-images.githubusercontent.com/12587127/77914470-e23fab00-728d-11ea-8e86-1badeec55831.png)

![image](https://user-images.githubusercontent.com/12587127/77914556-ff747980-728d-11ea-98ae-8e8b91a65614.png)

**Comment by chrispreisler** [comment]
Aah okay I see, so then there is now way to calculate the ratio based on the data I get from the shopify storefront... 

But thank you very much for your help.

**Comment by travis-r6s** [comment]
No - but you can specify multiple image sizes using that `transformSrc` field, as the example I give.
