### ISSUE TITLE
ProductVariants as a first class content type

### ISSUE THREAD

**Issue by adamJLev** [thetre97/gridsome-source-shopify#34]
Hey there, thx for the plugin it has been useful already!

It would be really useful to pull in the ProductVariants too, so one can query based on that.
The main use case for this for me is that Contentful's Shopify product picker integration returns a Variant ID instead of a Product ID.
https://www.contentful.com/developers/docs/extensibility/apps/shopify/

I am trying to get this project just done now so I wont have time to submit a PR , but if you think this would be a quick fix would be awesome to see this land soon! 😄 

thx!

**Comment by travis-r6s** [comment]
Hello,

Sure, this was an easy fix - not sure why I didn't do it in the first place...
Anyhow, released with no breaking changes in `v0.1.12`. Let me know if it does/doesn't solve  your problem...

Travis

**Comment by adamJLev** [comment]
Wow that was fast 🚀 👏 
Thanks, its working perfectly :)

(for future refernece and for anyone that wanders into this issue googling for solutions):
This allowed me to simply do this in my `gridsome.server.js`, to stich the types together in gridsome:

```js
module.exports = function (api) {
  api.loadSource(actions => {
    let contentfulProducts = actions.getCollection('ContentfulProduct')
    contentfulProducts.addReference('shopifyProductVariantId', 'ShopifyProductVariant')
```

and voila now I can query all my data in one query like this:
```graphql
query {
  allContentfulProduct {
    edges {
      node {
       name
        shopifyProductVariantId {
          id
          price {
            amount
          }
        }
      }
    }
  }
}

```

**Comment by travis-r6s** [comment]
Nice, I'll add that to the readme as an example...
