### ISSUE TITLE
Last version of Shopify Storefront API

### ISSUE THREAD

**Issue by ziopod** [thetre97/gridsome-source-shopify#45]
Hello,

Do you think if is possibe to update GraphQL queries to the [last stable version of Shopify Storefront API](https://shopify.dev/changelog/api-version-2020-04-is-now-stable-and-ready-for-general-usage)  (2020-04)

This would leave us with the pleasure of being able to use certain novelties, such as the possibility of accessing to the [new variants options](https://shopify.dev/docs/storefront-api/reference/object/productvariant?api[version]=2020-04) (like `currentlyNotInStock` or `quantityAvailable`)

Perhaps by allowing configuration of the API version ?

Thanks for your great work.

Sincerely

**Comment by travis-r6s** [comment]
Hey @ziopod - I certainly could, I don't think are any breaking changes.

It's worth noting that those above variant options aren't necessarily that useful at build time though. As `quantityAvailable` for example changes frequently, if you used those values in your build you would need to rebuild the site every time it changed (whenever someone purchases the product).

They are more useful for runtime queries, i.e. you use fetch to query that field when someone visits the product page.

**Comment by ziopod** [comment]
Thank you for your prompt response @thetre97 

Effectively, using fetch to avoid rebuild is smarter. And that's what i did.

For any reason, if i need to use a more recent api, what do suggest i do?

**Comment by travis-r6s** [comment]
If there are any particular fields you think should be added, feel free to edit `src/queries.js`, and create a PR.

**Comment by ziopod** [comment]
Yes, i saw that.

Right now, i'm using Fetch like you told me (it's more appropriate). If i ever need a query on the new Shopify API, i'll take the opportunity to create a PR.

Many thanks.
