### ISSUE TITLE
Getting an issue when attempting to run gridsome build

### ISSUE THREAD

**Issue by Simon-Renault** [thetre97/gridsome-source-shopify#68]
**Issue description**

When running `gridsome build` the build process unexpectedly stopped because of the following error : 

```
Initializing plugins...
Loading data from https://test_store_08B.myshopify.com

TypeError: Cannot read property 'data' of undefined
    at Object.transform (/Users/test_account/git/portfolio_shopify/node_modules/gridsome-source-shopify/lib/index.js:337:21)
    at AsyncGeneratorFunction.paginateEach [as each] (/Users/test_account/git/portfolio_shopify/node_modules/got/dist/source/create.js:180:45)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async queryAll (/Users/test_account/git/portfolio_shopify/node_modules/gridsome-source-shopify/lib/index.js:358:37)
    at async ShopifySource.getProductTypes (/Users/test_account/git/portfolio_shopify/node_modules/gridsome-source-shopify/lib/index.js:547:29)
    at async /Users/test_account/git/portfolio_shopify/node_modules/gridsome-source-shopify/lib/index.js:526:7
    at async Plugins.run (/Users/test_account/git/portfolio_shopify/node_modules/gridsome/lib/app/Plugins.js:141:11)
```

**Issue investigation**

I first though it was my mistake by accidentally entering a wrong shop name or storefront token, so verified and even tried to input a wrong one manually to see what happens.  The plugin have a clear error for wrong credentials so this is not linked to it.

I checked to see if my test shop was empty, but I had already added 2 products into two collections.

**Steps I followed**

- Created a new shopify shop
- Added a couple of mock products ( 4 products in two collections )
- Created a new private app and given it read and write access to everything
- Enabled the storefront API
- Made sure all products and collections had the private app as their sales channel
- Copied the shop name and the storefront token to my project and setup the plugin as per the documentation
- Got the error
- Tried the same credentials in the shopify starter example to make sure my code was not interfering, got the same error.

**Notes**

It is highly possible that this error is due to an error configuring shoppify, although it seems to me I followed the steps correctly I am pretty new to the storefront API.

**Comment by travis-r6s** [comment]
Thanks for reporting @Simon-Renault - you shouldn't need any Admin API permissions, but you will need to tick all Storefront permissions: 
![image](https://user-images.githubusercontent.com/12587127/94365178-9ea3ed80-00c6-11eb-8e5b-d398c4f6e046.png)

Are all these permissions ticked in your case?

**Comment by Simon-Renault** [comment]
Yes I can confirm they are all ticked

**Comment by Simon-Renault** [comment]
Would it be helpful If I shared the store name and storefront token ? It's a test store so I'd have no problem doing so.

I tied the same query in GraphiQL and encountered no issue at all.

I checked and the issue is happening to all the queries : 

```
api.loadSource(async actions => {
      console.log(`Loading data from ${options.storeUrl}`);

      await this.setupStore(actions);    //=> issue
      await this.getProductTypes(actions);  //=> issue
      await this.getProductTags(actions);  //=> issue
      await this.getCollections(actions);  //=> issue
      await this.getProducts(actions);  //=> issue
      await this.getBlogs(actions);  //=> issue
      await this.getArticles(actions);  //=> issue
      await this.getPages(actions);  //=> issue
 });
```

Tried to install the plugin on codesandbox ( witth the gridsome template ) but not working

**Comment by travis-r6s** [comment]
Yes, the storefront name and token would be useful, if you could share those...

**Comment by travis-r6s** [comment]
Also, the default Gridsome template on csb is at version 0.5, so you may need to update that first before it works...

**Comment by Simon-Renault** [comment]
Here they are : 

GRIDSOME_SHOPIFY_STOREFRONT= simon-renault
GRIDSOME_SHOPIFY_STOREFRONT_TOKEN = ca8bc7b82b8c5641f9de3e47b0990b42

I managed to make it work in code-sandbox, works like a charm and fetch all my data. Tried downloading the zip and run in my local environment : got the same error as before. 

https://codesandbox.io/s/nice-varahamihira-zehn7?file=/gridsome.config.js

**Comment by travis-r6s** [comment]
Thanks @Simon-Renault - can I also check what version of `gridsome-source-shopify` you are using locally? I'm running the starter locally with source version `0.2.4`, it it all seems to work... (albeit the build fails because there are no images for any of the products)

![image](https://user-images.githubusercontent.com/12587127/94372555-a24f6880-00f6-11eb-88dc-5bb50b92da57.png)

**Comment by Simon-Renault** [comment]
0.2.4 
The issue most likely from from the local environment, although hard to tell why.

**Comment by Simon-Renault** [comment]
Managed to fix the issue locally 

- Revertes node to v10.21.0
- Cleared the node and yarn cache
- deleted node modules
- deleted yarn.lock
- reinstalled everything 

Still have no clue what causes the issue in the first place. Will investigate more on this.

**Comment by travis-r6s** [comment]
Okay - let me know if you find out what the issue was, as I can't seem to reproduce it locally...

**Comment by dennisregalado** [comment]
Running into the same issue, this has to be an issue with the node version. Moving from Node `v13.8.0` to `stable` did the trick for me.
