### ISSUE TITLE
Trying to get comments in allShopifyArticle

### ISSUE THREAD

**Issue by antero10** [thetre97/gridsome-source-shopify#69]
Hello, I'm trying to get `comments` in allShopifyArticle query and it show that attribute is not available, what could be the problem?

Here is my query

```
query Publications {
  allShopifyArticle {
    edges {
      node {
        handle
        id
        image {
          originalSrc
        }
        seo {
          description
        }
        comments(first: 10) {
          edges {
            cursor
            node {
              author {
                email
              }
              content
            }
          }
        }
        title
        publishedAt
        
      }
    }
    totalCount
  }
}
```

Here is my error

```
{
  "error": {
    "errors": [
      {
        "message": "Cannot query field \"comments\" on type \"ShopifyArticle\". Did you mean \"content\"?",
        "stringified": "Cannot query field \"comments\" on type \"ShopifyArticle\". Did you mean \"content\"?\n\nGraphQL request:13:9\n12 |         }\n13 |         comments(first: 10) {\n   |         ^\n14 |           edges {"
      }
    ]
  }
}
```

I'm not sure what could be the problem. Please some help

**Comment by travis-r6s** [comment]
I just haven't added the comments field to the query, as I didn't think there would be much use for it - if you did fetch the comments in that query then it would only show the comments from when the site was last built, so it wouldn't always be up-to-date. It would usually make more sense to fetch the comments client-side, so you are always getting the latest comments.

**Comment by antero10** [comment]
Makes sense
