### ISSUE TITLE
Cannot get SEO in shopifyProduct

### ISSUE THREAD

**Issue by antero10** [thetre97/gridsome-source-shopify#70]
Hi, 

I'm having an error trying to get the `SEO` information in `shopifyProduct` mutation, here is my query

```
query Product($id:ID) {
  shopifyProduct(id: $id) {
    title
    description
    handle
    vendor
    productType
    seo {
      title
      description
    }
  }
}
```

Is there any chance I can get that info?

Thank you

**Comment by travis-r6s** [comment]
Hey @antero10 
I'm not sure that the field `seo` is available in the Storefront API? It only seems to be available in the Admin API.
https://shopify.dev/docs/storefront-api/reference/products/product?api%5Bversion%5D=2021-01
